apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /etc/localtime
        name: tz-config 
    imagePullPolicy: IfNotPresent
    name: busybox
  volumes:
  - name: tz-config
    hostPath:
       path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always
